export const DENTAL_TREATMENT_OPTIONS = {
  toothNumbers: [
    { label: "Tooth 1 - Upper Right 3rd Molar", value: "1" },
    { label: "Tooth 2 - Upper Right 2nd Molar", value: "2" },
    { label: "Tooth 3 - Upper Right 1st Molar", value: "3" },
    { label: "Tooth 4 - Upper Right 2nd Premolar", value: "4" },
    { label: "Tooth 5 - Upper Right 1st Premolar", value: "5" },
    { label: "Tooth 6 - Upper Right Canine", value: "6" },
    { label: "Tooth 7 - Upper Right Lateral Incisor", value: "7" },
    { label: "Tooth 8 - Upper Right Central Incisor", value: "8" },
    { label: "Tooth 9 - Upper Left Central Incisor", value: "9" },
    { label: "Tooth 10 - Upper Left Lateral Incisor", value: "10" },
    { label: "Tooth 11 - Upper Left Canine", value: "11" },
    { label: "Tooth 12 - Upper Left 1st Premolar", value: "12" },
    { label: "Tooth 13 - Upper Left 2nd Premolar", value: "13" },
    { label: "Tooth 14 - Upper Left 1st Molar", value: "14" },
    { label: "Tooth 15 - Upper Left 2nd Molar", value: "15" },
    { label: "Tooth 16 - Upper Left 3rd Molar", value: "16" },
    { label: "Tooth 17 - Lower Left 3rd Molar", value: "17" },
    { label: "Tooth 18 - Lower Left 2nd Molar", value: "18" },
    { label: "Tooth 19 - Lower Left 1st Molar", value: "19" },
    { label: "Tooth 20 - Lower Left 2nd Premolar", value: "20" },
    { label: "Tooth 21 - Lower Left 1st Premolar", value: "21" },
    { label: "Tooth 22 - Lower Left Canine", value: "22" },
    { label: "Tooth 23 - Lower Left Lateral Incisor", value: "23" },
    { label: "Tooth 24 - Lower Left Central Incisor", value: "24" },
    { label: "Tooth 25 - Lower Right Central Incisor", value: "25" },
    { label: "Tooth 26 - Lower Right Lateral Incisor", value: "26" },
    { label: "Tooth 27 - Lower Right Canine", value: "27" },
    { label: "Tooth 28 - Lower Right 1st Premolar", value: "28" },
    { label: "Tooth 29 - Lower Right 2nd Premolar", value: "29" },
    { label: "Tooth 30 - Lower Right 1st Molar", value: "30" },
    { label: "Tooth 31 - Lower Right 2nd Molar", value: "31" },
    { label: "Tooth 32 - Lower Right 3rd Molar", value: "32" },
  ],
  toothSurfaces: [
    { label: "Occlusal (O)", value: "O" },
    { label: "Mesial (M)", value: "M" },
    { label: "Distal (D)", value: "D" },
    { label: "Buccal (B)", value: "B" },
    { label: "Lingual (L)", value: "L" },
    { label: "Incisal (I)", value: "I" },
    { label: "MOD (Mesial-Occlusal-Distal)", value: "MOD" },
    { label: "MO (Mesial-Occlusal)", value: "MO" },
    { label: "OD (Occlusal-Distal)", value: "OD" },
    { label: "BL (Buccal-Lingual)", value: "BL" },
  ],
  treatmentTypes: [
    { label: "Restoration / Filling", value: "Restoration" },
    { label: "Extraction", value: "Extraction" },
    { label: "Root Canal Treatment", value: "RCT" },
    { label: "Scaling & Polishing", value: "Scaling" },
    { label: "Crown", value: "Crown" },
    { label: "Bridge", value: "Bridge" },
    { label: "Denture", value: "Denture" },
    { label: "Dental Implant", value: "Implant" },
    { label: "Orthodontic Treatment", value: "Orthodontic" },
    { label: "Periodontal Treatment", value: "Periodontal" },
    { label: "Fluoride Application", value: "Fluoride" },
    { label: "Fissure Sealant", value: "Sealant" },
    { label: "Bleaching / Whitening", value: "Bleaching" },
    { label: "Veneer", value: "Veneer" },
    { label: "Gum Surgery", value: "GumSurgery" },
    { label: "Biopsy", value: "Biopsy" },
  ],
  oralExaminationFindings: [
    { label: "Normal oral mucosa", value: "Normal" },
    { label: "Gingivitis", value: "Gingivitis" },
    { label: "Periodontitis", value: "Periodontitis" },
    { label: "Dental caries", value: "Caries" },
    { label: "Pulpitis", value: "Pulpitis" },
    { label: "Periapical abscess", value: "Abscess" },
    { label: "Oral ulcer", value: "Ulcer" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Erythroplakia", value: "Erythroplakia" },
    { label: "Oral candidiasis", value: "Candidiasis" },
    { label: "Oral lichen planus", value: "LichenPlanus" },
    { label: "TMJ disorder", value: "TMJ" },
    { label: "Malocclusion", value: "Malocclusion" },
    { label: "Impacted tooth", value: "Impacted" },
    { label: "Missing tooth", value: "Missing" },
    { label: "Fractured tooth", value: "Fractured" },
    { label: "Worn dentition / Attrition", value: "Attrition" },
  ],
  periodontalCharting: [
    { label: "Probing Depth 1-3mm (Healthy)", value: "1-3" },
    { label: "Probing Depth 4-5mm (Mild)", value: "4-5" },
    { label: "Probing Depth 6-7mm (Moderate)", value: "6-7" },
    { label: "Probing Depth 8mm+ (Severe)", value: "8+" },
    { label: "Bleeding on Probing (BOP)", value: "BOP" },
    { label: "Gingival Recession", value: "Recession" },
    { label: "Furcation Involvement", value: "Furcation" },
    { label: "Mobility Grade I", value: "Mobility1" },
    { label: "Mobility Grade II", value: "Mobility2" },
    { label: "Mobility Grade III", value: "Mobility3" },
  ],
  anaesthesiaTypes: [
    { label: "Local Anaesthesia", value: "Local" },
    { label: "Regional Block", value: "Regional" },
    { label: "General Anaesthesia", value: "General" },
    { label: "Sedation (IV)", value: "SedationIV" },
    { label: "Inhalation Sedation", value: "Inhalation" },
  ],
  radiographTypes: [
    { label: "Intraoral Periapical (IOPA)", value: "IOPA" },
    { label: "Bitewing", value: "Bitewing" },
    { label: "Occlusal", value: "Occlusal" },
    { label: "Panoramic (OPG)", value: "OPG" },
    { label: "Cephalometric", value: "Cephalometric" },
    { label: "CBCT", value: "CBCT" },
  ],
  labOrderTypes: [
    { label: "Crown (PFM)", value: "CrownPFM" },
    { label: "Crown (Full Cast)", value: "CrownFullCast" },
    { label: "Crown (Zirconia)", value: "CrownZirconia" },
    { label: "Crown (E-max)", value: "CrownEmax" },
    { label: "Bridge", value: "Bridge" },
    { label: "Partial Denture (Acrylic)", value: "PartialAcrylic" },
    { label: "Partial Denture (Cast Partial)", value: "PartialCast" },
    { label: "Complete Denture", value: "CompleteDenture" },
    { label: "Veneer", value: "Veneer" },
    { label: "Inlay / Onlay", value: "InlayOnlay" },
    { label: "Orthodontic Appliance", value: "OrthoAppliance" },
    { label: "Night Guard", value: "NightGuard" },
    { label: "Surgical Guide", value: "SurgicalGuide" },
  ],
};

export const ORAL_EXAMINATION_FINDINGS = {
  lips: [
    { label: "Normal", value: "Normal" },
    { label: "Dry / Chapped", value: "Dry" },
    { label: "Ulceration", value: "Ulceration" },
    { label: "Angular Cheilitis", value: "AngularCheilitis" },
    { label: "Herpes Labialis", value: "Herpes" },
    { label: "Cleft Lip", value: "CleftLip" },
    { label: "Swelling", value: "Swelling" },
    { label: "Pigmentation", value: "Pigmentation" },
  ],
  buccalMucosa: [
    { label: "Normal", value: "Normal" },
    { label: "Hyperkeratosis", value: "Hyperkeratosis" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Erythroplakia", value: "Erythroplakia" },
    { label: "Lichen Planus", value: "LichenPlanus" },
    { label: "Ulceration", value: "Ulceration" },
    { label: "Fibroma", value: "Fibroma" },
    { label: "Linea Alba", value: "LineaAlba" },
  ],
  tongue: [
    { label: "Normal", value: "Normal" },
    { label: "Coated / Furred", value: "Coated" },
    { label: "Geographic Tongue", value: "Geographic" },
    { label: "Fissured Tongue", value: "Fissured" },
    { label: "Atrophic / Smooth", value: "Atrophic" },
    { label: "Ulceration", value: "Ulceration" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Macroglossia", value: "Macroglossia" },
  ],
  floorOfMouth: [
    { label: "Normal", value: "Normal" },
    { label: "Swelling", value: "Swelling" },
    { label: "Ranula", value: "Ranula" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Calculus", value: "Calculus" },
  ],
  palate: [
    { label: "Normal", value: "Normal" },
    { label: "High Arched", value: "HighArched" },
    { label: "Cleft Palate", value: "CleftPalate" },
    { label: "Erythema", value: "Erythema" },
    { label: "Petechiae", value: "Petechiae" },
    { label: "Toras Palatinus", value: "TorasPalatinus" },
  ],
  oropharynx: [
    { label: "Normal", value: "Normal" },
    { label: "Erythema", value: "Erythema" },
    { label: "Tonsillar Enlargement", value: "TonsillarEnlargement" },
    { label: "Exudate", value: "Exudate" },
    { label: "Ulceration", value: "Ulceration" },
  ],
  gingiva: [
    { label: "Normal / Healthy", value: "Normal" },
    { label: "Gingivitis", value: "Gingivitis" },
    { label: "Periodontitis", value: "Periodontitis" },
    { label: "Hyperplasia", value: "Hyperplasia" },
    { label: "Recession", value: "Recession" },
    { label: "Swelling", value: "Swelling" },
    { label: "Bleeding on Probing", value: "BOP" },
    { label: "Fistula / Sinus Tract", value: "Fistula" },
  ],
  salivaryGlands: [
    { label: "Normal", value: "Normal" },
    { label: "Enlarged", value: "Enlarged" },
    { label: "Tender", value: "Tender" },
    { label: "Reduced Saliva Flow", value: "ReducedFlow" },
    { label: "Sialolith (Calculus)", value: "Sialolith" },
  ],
};

export const DENTAL_CHART_OPTIONS = {
  toothStatus: [
    { label: "Present", value: "Present" },
    { label: "Missing", value: "Missing" },
    { label: "Impacted", value: "Impacted" },
    { label: "Fractured", value: "Fractured" },
    { label: "Root Stump", value: "RootStump" },
    { label: "Partially Erupted", value: "PartiallyErupted" },
  ],
  cariesStatus: [
    { label: "Sound (Healthy)", value: "Sound" },
    { label: "Decayed / Carious", value: "Decayed" },
    { label: "Filled (Restored)", value: "Filled" },
    { label: "Filled with Decay", value: "FilledDecay" },
    { label: "Missing due to Caries", value: "MissingCaries" },
    { label: "Fissure Sealant", value: "Sealant" },
  ],
  mobility: [
    { label: "None (Grade 0)", value: "0" },
    { label: "Grade I (1mm)", value: "1" },
    { label: "Grade II (2mm)", value: "2" },
    { label: "Grade III (3mm+)", value: "3" },
  ],
  furcationInvolvement: [
    { label: "None", value: "None" },
    { label: "Grade I (Early)", value: "I" },
    { label: "Grade II (Definite)", value: "II" },
    { label: "Grade III (Through & Through)", value: "III" },
  ],
};

export const CATARACT_SURGERY_RECORD_OPTIONS = {
  eyeOptions: [
    { label: "Right Eye (OD)", value: "OD" },
    { label: "Left Eye (OS)", value: "OS" },
    { label: "Both Eyes (OU)", value: "OU" },
  ],
  surgeryTypes: [
    { label: "Phacoemulsification", value: "Phaco" },
    { label: "ECCE", value: "ECCE" },
    { label: "ICCE", value: "ICCE" },
  ],
  lensTypes: [
    { label: "Monofocal IOL", value: "Monofocal" },
    { label: "Multifocal IOL", value: "Multifocal" },
    { label: "Toric IOL", value: "Toric" },
  ],
};
